esphome:
  name: kitchen_fan
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret net1
  password: !secret net1_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.2.18
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.252.0  
  
mqtt:
  broker:   !secret mqtt
  username: vent_kitchen
  password: !secret mqtt_pass

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass
  reboot_timeout: 0s

ota:
  password: !secret ota_pass
  
web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - fan.toggle: fan_1

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
    id: kitchen_fan_status
    pin:
      number: GPIO13
      inverted: True

fan:
  - platform: binary
    output: relay
    id: fan_1
    name: "Kitchen Fan"
